todoweb/urls.py
from django.contrib import admin
from django.urls import path
from todoapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name = "home"),
    path('config/<slug>/', views.ConfigureView, name = "config"),
    path('delete/<slug>/' , views.deletelist_or_task, name = "delete"),
    path('edititem/<slug>/' , views.edit_item, name = 'edititem'),
    path('addlist', views.addlist, name = "addlist"),
    path('login/', views.loginuser, name = 'login')
]

todoapp/models.py
from django.db import models
from autoslug import AutoSlugField

# Create your models here.


class ListModel(models.Model):
    title = models.CharField(max_length=250)
    slug = AutoSlugField(populate_from = 'title' , unique = True , null = True)
    def __str__(self):
        return self.title

class Tasks(models.Model):
    name = models.CharField(max_length=250)
    catagory = models.ForeignKey(ListModel, on_delete= models.CASCADE)
    slug = AutoSlugField(populate_from = 'name' , unique = True , null = True)

    def __str__(self):
        return self.name
    

todoapp/forms.py
from django import forms
from .models import ListModel , Tasks

class ListForm(forms.ModelForm):
    class Meta:
        model = ListModel
        fields = "__all__"

class Tasks(forms.ModelForm):
    class Meta:
        model = Tasks
        fields = ('__all__')

todoapp/views.py
from django.shortcuts import render , redirect
from .models import ListModel,Tasks
from .forms import ListForm

# Create your views here.

def homepage(request):
    a = ListModel.objects.all()
    data = {
        'item' : a
    }
    return render(request, "home.html" , data)

def ConfigureView(request, slug):
    a = ListModel.objects.get(slug=slug)
    if request.method == "POST":
        task = request.POST['task'].strip()
        if task != "" :
            t = Tasks(name = task , catagory = a)
            t.save()


    data = {
        'i' : a
    }
    return render(request, "configure.html" , data)

def deletelist_or_task(request,slug):
    try:
        li = ListModel.objects.get(slug = slug)
        li.delete()
        return redirect("home")
    except:
        tsk = Tasks.objects.get(slug = slug)
        tsk.delete()
        return redirect("home")

def edit_item(request,slug):
    try:
        obj = Tasks.objects.get(slug=slug)
        if request.method == "POST":
            value = request.POST.get('editeditem')
            obj.name = value
            obj.save()
            return redirect("home")

    except:
        obj = ListModel.objects.get(slug=slug)
        if request.method == "POST":
            value = request.POST.get('editeditem')
            obj.title = value
            obj.save()
            return redirect("home")

    data = {
        'item' : obj
    }

    return render(request, "editform.html" , data)


def addlist(request):
    f = ListForm()
    if request.method == "POST":
        f = ListForm(request.POST)
        if f.is_valid():
            f.save()
            return redirect("home")
    return render(request, "addlist.html", {'form' : f})

todoapp/templates/addlist.html
<form action="" method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit">submit</button>
</form>

todoapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>
    {% block title %}
        
    {% endblock title %}
        </title>
  </head>
  <body>
    
    {% block content %}
        
    {% endblock content %}
        

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

todoapp/templates/configure.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{i}}</h1> <a href="{% url 'edititem' slug=i.slug %}">Edit</a>
    {% for k in i.tasks_set.all %}
        {{k.name}} <a href="{% url 'edititem' slug=k.slug %}"><button>Edit</button></a><a href="{% url 'delete' slug=k.slug %}"><button>Delete</button></a> <br>
        {{k.description}}
    {% endfor %}

    <form action="" method="post">
        {% csrf_token %}
        <input type="text" name = "task">
        <button type="submit">Add</button>
    </form>
    {{m}}


    <a href="{% url 'delete' slug=i.slug %}">Delete {{i}}</a>
</body>
</html>

todoapp/templates/editform.html
{% extends 'base.html' %}

{% block content %}
    
<form action="" method="post">
    {% csrf_token %}
    <input type="text" name="editeditem" required value="{{item}}">
    <button type="submit">Save</button>

</form>


{% endblock content %}
    

todoapp/templates/home.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'addlist' %} "><button>Add Catagory</button></a>
{% for i in item %}

<h1>{{i}}</h1> <a href="{% url 'config' slug=i.slug %}">Configure</a> <br>
{% for k in i.tasks_set.all %}
        {{k.name}}
        {{k.description}}
{% endfor %}
{% endfor %} 

{% endblock content %}
    

todoapp/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock title %}


{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        Username: <input type="text" name = 'username' placeholder="username"><br>
        Password : <input type="password" name='password' placeholder="password"><br>
        <button type="submit">Login</button>
    </form>

    
    {% for message in messages %}
        {{message}}
    {% endfor %}
        
{% endblock content %}
    